import type { Theorem } from './types.ts';
// Content is independent of the page renderer so other catalogue sections can
// use the same statement / conditions / example / proof / reference structure.
const oeis = (id: string) => ({
  label: `OEIS ${id}: formulas and references`,
  url: `https://oeis.org/${id}`,
});
const result = (
  id: string,
  title: string,
  kind: string,
  conditions: string,
  statement: string,
  example: string,
  proof: string,
  reference: Theorem['reference'],
  related: string[] = [],
) => ({
  id,
  title,
  kind,
  conditions,
  statement,
  example,
  proof,
  reference,
  related,
});
export const sequenceTheorems: Record<string, Theorem[]> = {
  squares: [
    result(
      'odd-number-sum',
      'Sum of consecutive odd numbers',
      'Identity',
      'Integer n ≥ 0; an empty sum is 0.',
      '1 + 3 + ⋯ + (2n − 1) = n²',
      'For n = 5: 1 + 3 + 5 + 7 + 9 = 25.',
      'The difference k² − (k − 1)² is 2k − 1. Summing these differences from k = 1 to n cancels every intermediate square, leaving n². Geometrically, each odd number adds one border to the square.',
      oeis('A000290'),
    ),
    result(
      'sum-of-squares',
      'Sum of squares',
      'Identity',
      'Integer n ≥ 0.',
      '1² + 2² + ⋯ + n² = n(n + 1)(2n + 1) / 6',
      'For n = 4: 1 + 4 + 9 + 16 = 30.',
      'Let Q(n) = n(n + 1)(2n + 1)/6. Direct expansion gives Q(n) − Q(n − 1) = n², and Q(0) = 0. Summing the differences proves the formula.',
      oeis('A000290'),
      ['cubes'],
    ),
  ],
  cubes: [
    result(
      'sum-of-cubes',
      'Sum of cubes',
      'Identity',
      'Integer n ≥ 0; Tₙ = n(n + 1)/2.',
      '1³ + 2³ + ⋯ + n³ = Tₙ²',
      'For n = 4: 1 + 8 + 27 + 64 = 100 = 10².',
      'Tₖ² − Tₖ₋₁² = (Tₖ − Tₖ₋₁)(Tₖ + Tₖ₋₁) = k · k² = k³. Sum from k = 1 to n; the left side telescopes to Tₙ².',
      oeis('A000578'),
      ['triangular', 'squares'],
    ),
    result(
      'cube-residues',
      'Cubes modulo 9',
      'Congruence',
      'Any integer m. Congruence modulo 9 means the difference is divisible by 9.',
      'm³ ≡ 0, 1, or −1 (mod 9)',
      '8³ = 512 = 9 × 57 − 1, so 8³ ≡ −1 (mod 9).',
      'Write m as 3k, 3k + 1, or 3k − 1. Their cubes are respectively congruent to 0, 1, and −1 modulo 9. This is a necessary test for a cube, not a sufficient one: 10 ≡ 1 modulo 9 but is not a cube.',
      oeis('A000578'),
    ),
  ],
  fibonacci: [
    result(
      'binet',
      'Binet’s formula',
      'Theorem',
      'Integer n ≥ 0; φ = (1 + √5)/2 and ψ = (1 − √5)/2.',
      'Fₙ = (φⁿ − ψⁿ) / √5',
      'For n = 3: (φ³ − ψ³)/√5 = 2 = F₃.',
      'Both φ and ψ satisfy x² = x + 1, so their powers satisfy the Fibonacci recurrence. The displayed expression has starting values 0 and 1, hence equals Fₙ by induction. The identity is exact, but evaluating it with floating-point arithmetic can introduce rounding errors; the calculator uses integer addition.',
      {
        label: 'NIST DLMF §26.11, equation 7',
        url: 'https://dlmf.nist.gov/26.11.E7',
      },
    ),
    result(
      'fibonacci-square-sum',
      'Sum of squared Fibonacci numbers',
      'Identity',
      'Integer n ≥ 0; F₀ = 0 and F₁ = 1.',
      'F₁² + F₂² + ⋯ + Fₙ² = FₙFₙ₊₁',
      'For n = 5: 1 + 1 + 4 + 9 + 25 = 40 = 5 × 8.',
      'For k ≥ 1, FₖFₖ₊₁ − Fₖ₋₁Fₖ = Fₖ(Fₖ₊₁ − Fₖ₋₁) = Fₖ². Summing cancels intermediate products. The square tiling above gives the same identity as a rectangle area.',
      oeis('A000045'),
      ['squares'],
    ),
  ],
  triangular: [
    result(
      'triangular-square-test',
      'Recognising triangular numbers',
      'Characterisation',
      'Integer m ≥ 0.',
      'm is triangular if and only if 8m + 1 is an odd perfect square.',
      'For m = 15: 8 × 15 + 1 = 121 = 11², giving n = (11 − 1)/2 = 5.',
      'If m = n(n + 1)/2, then 8m + 1 = (2n + 1)². Conversely, if 8m + 1 = r² with r a positive odd integer, n = (r − 1)/2 is a nonnegative integer and substitution gives m = Tₙ.',
      oeis('A000217'),
      ['squares'],
    ),
    result(
      'consecutive-triangles',
      'Two triangular numbers form a square',
      'Identity',
      'Integer n ≥ 1.',
      'Tₙ + Tₙ₋₁ = n²',
      'For n = 5: 15 + 10 = 25.',
      'Add n(n + 1)/2 and n(n − 1)/2 to obtain n². Equivalently, divide an n × n dot square along its diagonal: one part has rows 1 through n, and the other has rows 1 through n − 1.',
      oeis('A000217'),
      ['squares'],
    ),
  ],
  pentagonal: [
    result(
      'pentagonal-decomposition',
      'Pentagonal decomposition',
      'Identity',
      'Integer n ≥ 1.',
      'Pₙ = n + 3Tₙ₋₁',
      'For n = 4: 22 = 4 + 3 × 6.',
      'Substitute Tₙ₋₁ = n(n − 1)/2. Then n + 3n(n − 1)/2 = n(3n − 1)/2. This decomposes the vertex-based polygonal count into a line of n dots and three triangular counts.',
      oeis('A000326'),
      ['triangular'],
    ),
    result(
      'pentagonal-square-test',
      'Recognising pentagonal numbers',
      'Characterisation',
      'Integer m > 0. The zero term P₀ = 0 is handled separately.',
      'm is pentagonal ⇔ 24m + 1 = r² for a positive integer r with r ≡ 5 (mod 6).',
      'For m = 22: 24 × 22 + 1 = 529 = 23²; (23 + 1)/6 = 4.',
      'The formula gives 24Pₙ + 1 = (6n − 1)². Conversely, the stated condition makes n = (r + 1)/6 a positive integer; substitution gives Pₙ = m. A square alone is not enough: m = 2 gives 49, but (7 + 1)/6 is not an integer.',
      oeis('A000326'),
      ['squares'],
    ),
  ],
  hexagonal: [
    result(
      'hexagonal-triangular',
      'Every hexagonal number is triangular',
      'Identity',
      'Integer n ≥ 1; H₀ = T₀ = 0 separately.',
      'Hₙ = T₂ₙ₋₁',
      'For n = 4: H₄ = 28 = T₇.',
      'T₂ₙ₋₁ = (2n − 1)(2n)/2 = n(2n − 1) = Hₙ. Thus the positive hexagonal numbers are precisely the triangular numbers at odd indices. Not every triangular number is hexagonal; T₂ = 3 is an example.',
      oeis('A000384'),
      ['triangular'],
    ),
    result(
      'hexagonal-sum',
      'Sum of hexagonal numbers',
      'Identity',
      'Integer n ≥ 0.',
      'H₁ + H₂ + ⋯ + Hₙ = n(n + 1)(4n − 1) / 6',
      'For n = 4: 1 + 6 + 15 + 28 = 50.',
      'Since Hₖ = 2k² − k, the sum is twice the sum of squares minus the sum of integers. Substitute n(n + 1)(2n + 1)/6 and n(n + 1)/2, then simplify.',
      oeis('A000384'),
      ['squares', 'triangular'],
    ),
  ],
  'powers-of-two': [
    result(
      'binary-geometric-sum',
      'Finite geometric sum',
      'Identity',
      'Integer n ≥ 0.',
      '1 + 2 + 2² + ⋯ + 2ⁿ = 2ⁿ⁺¹ − 1',
      'For n = 4: 1 + 2 + 4 + 8 + 16 = 31.',
      'Call the sum S. Subtract S from 2S: all intermediate powers cancel and S = 2ⁿ⁺¹ − 1 remains. In the diagram, this counts all nodes through depth n, whereas 2ⁿ counts just the leaves.',
      oeis('A000079'),
    ),
    result(
      'subset-count',
      'Number of subsets',
      'Counting theorem',
      'A finite set with n elements, where n ≥ 0.',
      'An n-element set has exactly 2ⁿ subsets.',
      'A three-element set has 1 empty subset, 3 singletons, 3 pairs, and 1 full subset: 8 in total.',
      'For each element choose either inclusion or exclusion. Each string of n binary choices determines exactly one subset, and each subset determines one string. Multiplying the two choices at each position gives 2ⁿ. For n = 0 there is one subset, the empty set.',
      oeis('A000079'),
    ),
  ],
  primes: [
    result(
      'euclid',
      'Euclid’s theorem',
      'Theorem',
      'Primes are positive integers greater than 1 with exactly two positive divisors.',
      'There are infinitely many prime numbers.',
      'For the list 2, 3, 5, the number 2 × 3 × 5 + 1 = 31 has a prime divisor outside the list.',
      'Given any finite list of primes, form their product plus 1. This integer is greater than 1, so it has a prime divisor. Division by each listed prime leaves remainder 1; therefore that divisor is not on the list. The product plus 1 need not itself be prime: 2 × 3 × 5 × 7 × 11 × 13 + 1 = 30031 = 59 × 509.',
      {
        label: 'Euclid, Elements IX.20',
        url: 'https://mathcs.clarku.edu/~djoyce/elements/bookIX/propIX20.html',
      },
    ),
    result(
      'unique-factorisation',
      'Fundamental theorem of arithmetic',
      'Theorem',
      'Integer m > 1; order of the factors is ignored.',
      'Every integer greater than 1 has a unique factorisation into primes.',
      '360 = 2³ × 3² × 5. Rearranging these factors does not give a different factorisation.',
      'Existence follows by induction: a composite integer splits into smaller factors until only primes remain. For uniqueness, use Euclid’s lemma: if a prime divides a product, it divides a factor. A prime in one factorisation must therefore occur in the other; cancel it and repeat.',
      {
        label: 'NIST DLMF §27.2, fundamental theorem of arithmetic',
        url: 'https://dlmf.nist.gov/27.2#i',
      },
    ),
  ],
};
