import {
  arccosine,
  arcsine,
  arctangent,
  cosine,
  PI,
  sine,
  tangent,
} from './trig-math.ts';
import type { TrigFunction } from './types.ts';
const source = {
  label: 'NIST DLMF: trigonometric identities',
  url: 'https://dlmf.nist.gov/4.21',
};
const inverseSource = {
  label: 'NIST DLMF: inverse trigonometric functions',
  url: 'https://dlmf.nist.gov/4.23',
};
const theorem = (
  id: string,
  title: string,
  conditions: string,
  statement: string,
  example: string,
  proof: string,
  related: string[] = [],
  inverse = false,
) => ({
  id,
  title,
  kind: 'Identity',
  conditions,
  statement,
  example,
  proof,
  related,
  reference: inverse ? inverseSource : source,
});
export const trigFunctions: TrigFunction[] = [
  {
    id: 'sin',
    name: 'Sine',
    notation: 'sin(θ)',
    description: 'The vertical coordinate of a point on the unit circle.',
    inverse: false,
    fn: sine,
    initial: PI / 6,
    domain: 'All real angles',
    range: '[−1, 1]',
    period: '2π radians · 360°',
    parity: 'Odd: sin(−θ) = −sin(θ)',
    derivative: 'cos(θ)',
    formula: 'sin(θ) = opposite / hypotenuse',
    explanation:
      'For an acute angle in a right triangle, sine is the opposite side divided by the hypotenuse. On the unit circle, it is the y-coordinate for any angle.',
    graph: [-2 * PI, 2 * PI, -1.4, 1.4],
    related: ['cos', 'arcsin'],
    theorems: [
      theorem(
        'pythagorean',
        'Pythagorean identity',
        'Any real angle θ.',
        'sin²(θ) + cos²(θ) = 1.',
        'At θ = π/6: (1/2)² + (√3/2)² = 1.',
        'The unit-circle point has coordinates (cos θ, sin θ) and distance 1 from the origin. Apply the Pythagorean theorem.',
        ['cos'],
      ),
      theorem(
        'sine-addition',
        'Angle addition',
        'Any real angles α and β.',
        'sin(α + β) = sin(α)cos(β) + cos(α)sin(β).',
        'sin(π/6 + π/6) = √3/2.',
        'Rotate the vector (cos α, sin α) by β. The rotation matrix has second row (sin β, cos β), giving the new vertical coordinate.',
        ['cos'],
      ),
    ],
  },
  {
    id: 'cos',
    name: 'Cosine',
    notation: 'cos(θ)',
    description: 'The horizontal coordinate of a point on the unit circle.',
    inverse: false,
    fn: cosine,
    initial: PI / 3,
    domain: 'All real angles',
    range: '[−1, 1]',
    period: '2π radians · 360°',
    parity: 'Even: cos(−θ) = cos(θ)',
    derivative: '−sin(θ)',
    formula: 'cos(θ) = adjacent / hypotenuse',
    explanation:
      'For an acute angle in a right triangle, cosine is the adjacent side divided by the hypotenuse. On the unit circle, it is the x-coordinate for any angle.',
    graph: [-2 * PI, 2 * PI, -1.4, 1.4],
    related: ['sin', 'arccos'],
    theorems: [
      theorem(
        'cosine-addition',
        'Angle addition',
        'Any real angles α and β.',
        'cos(α + β) = cos(α)cos(β) − sin(α)sin(β).',
        'cos(π/6 + π/6) = 3/4 − 1/4 = 1/2.',
        'Rotate (cos α, sin α) by β. The first row of the rotation matrix is (cos β, −sin β), which gives the horizontal coordinate.',
        ['sin'],
      ),
      theorem(
        'cosine-double',
        'Double-angle identity',
        'Any real angle θ.',
        'cos(2θ) = 2cos²(θ) − 1 = 1 − 2sin²(θ).',
        'At θ = π/4, cos(π/2) = 2(1/2) − 1 = 0.',
        'Set α = β = θ in the cosine addition formula, then use sin² θ + cos² θ = 1.',
        ['sin'],
      ),
    ],
  },
  {
    id: 'tan',
    name: 'Tangent',
    notation: 'tan(θ)',
    description:
      'The slope of the unit-circle radius, where its horizontal coordinate is nonzero.',
    inverse: false,
    fn: tangent,
    initial: PI / 4,
    domain: 'θ ≠ π/2 + kπ, for any integer k',
    range: 'All real numbers',
    period: 'π radians · 180°',
    parity: 'Odd: tan(−θ) = −tan(θ)',
    derivative: '1 / cos²(θ)',
    formula: 'tan(θ) = sin(θ) / cos(θ)',
    explanation:
      'Tangent is the slope y/x of the radius. At odd multiples of π/2 the radius is vertical and tangent is undefined. Dashed lines on the graph mark these poles.',
    graph: [-2 * PI, 2 * PI, -5, 5],
    related: ['sin', 'cos', 'arctan'],
    theorems: [
      theorem(
        'tangent-pythagorean',
        'Tangent and secant',
        'cos(θ) ≠ 0; sec(θ) means 1/cos(θ).',
        '1 + tan²(θ) = 1 / cos²(θ).',
        'At θ = π/4, 1 + 1 = 1/(1/2) = 2.',
        'Divide sin² θ + cos² θ = 1 by cos² θ. Division is valid only away from the tangent poles.',
        ['cos'],
      ),
      theorem(
        'tangent-addition',
        'Angle addition',
        'cos(α), cos(β), and cos(α + β) are all nonzero.',
        'tan(α + β) = (tan(α) + tan(β)) / (1 − tan(α)tan(β)).',
        'tan(π/6 + π/6) = √3.',
        'Divide the sine addition formula by the cosine addition formula, then divide numerator and denominator by cos α cos β. The assumptions ensure every denominator is nonzero.',
        ['sin', 'cos'],
      ),
    ],
  },
  {
    id: 'arcsin',
    name: 'Arcsine',
    notation: 'arcsin(x)',
    description: 'The principal angle whose sine is x.',
    inverse: true,
    fn: arcsine,
    initial: 0.5,
    domain: '[−1, 1]',
    range: '[−π/2, π/2] · [−90°, 90°]',
    period: 'Not periodic',
    parity: 'Odd: arcsin(−x) = −arcsin(x)',
    derivative: '1 / √(1 − x²), for −1 < x < 1',
    formula: 'θ = arcsin(x) ⇔ sin(θ) = x, −π/2 ≤ θ ≤ π/2',
    explanation:
      'A horizontal line at height x usually meets the unit circle twice. Arcsine chooses the point on the right half, so its angle lies between −π/2 and π/2.',
    graph: [-1, 1, -1.8, 1.8],
    related: ['sin', 'arccos'],
    theorems: [
      theorem(
        'arcsine-inverse',
        'Inverse identities and branch restriction',
        '−1 ≤ x ≤ 1. For the second identity, −π/2 ≤ θ ≤ π/2.',
        'sin(arcsin(x)) = x; arcsin(sin(θ)) = θ only on the stated angle interval.',
        'arcsin(sin(5π/6)) = π/6, not 5π/6.',
        'Sine is continuous and strictly increasing on [−π/2, π/2], mapping it onto [−1, 1]. Its inverse is defined on exactly that restriction.',
        ['sin'],
        true,
      ),
      theorem(
        'inverse-complement',
        'Complementary inverse angles',
        '−1 ≤ x ≤ 1.',
        'arcsin(x) + arccos(x) = π/2.',
        'arcsin(1/2) + arccos(1/2) = π/6 + π/3 = π/2.',
        'If θ = arcsin x, then cos(π/2 − θ) = x and π/2 − θ lies in [0, π], the principal arccosine range.',
        ['arccos'],
        true,
      ),
    ],
  },
  {
    id: 'arccos',
    name: 'Arccosine',
    notation: 'arccos(x)',
    description: 'The principal angle whose cosine is x.',
    inverse: true,
    fn: arccosine,
    initial: 0.5,
    domain: '[−1, 1]',
    range: '[0, π] · [0°, 180°]',
    period: 'Not periodic',
    parity: 'Neither odd nor even',
    derivative: '−1 / √(1 − x²), for −1 < x < 1',
    formula: 'θ = arccos(x) ⇔ cos(θ) = x, 0 ≤ θ ≤ π',
    explanation:
      'A vertical line at horizontal coordinate x usually meets the circle twice. Arccosine chooses the point on the upper half, with an angle from 0 to π.',
    graph: [-1, 1, -0.3, 3.5],
    related: ['cos', 'arcsin'],
    theorems: [
      theorem(
        'arccosine-inverse',
        'Inverse identities and branch restriction',
        '−1 ≤ x ≤ 1. For the second identity, 0 ≤ θ ≤ π.',
        'cos(arccos(x)) = x; arccos(cos(θ)) = θ only on the stated angle interval.',
        'arccos(cos(−π/3)) = π/3.',
        'Cosine is continuous and strictly decreasing from 1 to −1 on [0, π]. Inverting that restriction selects a unique angle.',
        ['cos'],
        true,
      ),
      theorem(
        'arccosine-reflection',
        'Reflection identity',
        '−1 ≤ x ≤ 1.',
        'arccos(−x) = π − arccos(x).',
        'arccos(−1/2) = 2π/3.',
        'If θ = arccos x, then cos(π − θ) = −x. Since π − θ remains in [0, π], it is the principal angle for −x.',
        ['cos'],
        true,
      ),
    ],
  },
  {
    id: 'arctan',
    name: 'Arctangent',
    notation: 'arctan(x)',
    description: 'The principal angle of a line with slope x.',
    inverse: true,
    fn: arctangent,
    initial: 1,
    domain: 'All real numbers',
    range: '(−π/2, π/2) · (−90°, 90°)',
    period: 'Not periodic',
    parity: 'Odd: arctan(−x) = −arctan(x)',
    derivative: '1 / (1 + x²)',
    formula: 'θ = arctan(x) ⇔ tan(θ) = x, −π/2 < θ < π/2',
    explanation:
      'A line through the origin with slope x meets the circle twice. Arctangent chooses the point on the right half. Its angle approaches, but never reaches, ±π/2 for finite x.',
    graph: [-5, 5, -1.8, 1.8],
    related: ['tan', 'arcsin'],
    theorems: [
      theorem(
        'arctangent-inverse',
        'Inverse identities and branch restriction',
        'Any real x. For the second identity, −π/2 < θ < π/2.',
        'tan(arctan(x)) = x; arctan(tan(θ)) = θ only on the stated angle interval.',
        'arctan(tan(3π/4)) = −π/4.',
        'Tangent is continuous and strictly increasing from −∞ to ∞ between its poles at −π/2 and π/2. Restricting to that interval defines its inverse.',
        ['tan'],
        true,
      ),
      theorem(
        'arctangent-reciprocal',
        'Reciprocal identity',
        'Real x > 0.',
        'arctan(x) + arctan(1/x) = π/2.',
        'arctan(1) + arctan(1) = π/4 + π/4.',
        'In a right triangle with positive legs 1 and x, the two acute angles have tangents x and 1/x and sum to π/2. For x < 0, the corresponding sum is −π/2.',
        ['tan'],
        true,
      ),
    ],
  },
];
export const trigUrl = (f: { id: string }) => `/trigonometry/${f.id}`;
export function trigAtPath(pathname: string) {
  const path = pathname.replace(/\/$/, '');
  if (path === '/trigonometry') return { item: null };
  const item = trigFunctions.find((f) => trigUrl(f) === path);
  return item ? { item } : null;
}
export function evaluateTrig(
  item: TrigFunction,
  input: number,
  unit = 'radians',
) {
  if (!['radians', 'degrees'].includes(unit))
    throw new RangeError('Unknown angle unit.');
  const angleFactor = unit === 'degrees' ? PI / 180 : 1;
  const value = item.fn(item.inverse ? input : input * angleFactor);
  return item.inverse ? value / angleFactor : value;
}
